version: '3.8'
services:
  db:
    image: postgres:15.3
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tarefas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    deploy:
      replicas: 5
      placement:
        constraints: [node.role==worker]
  lista-tarefas:
    image: henriquedev/lista-tarefas:latest
    deploy:
      replicas: 5
      placement:
        constraints: [node.role==worker]
    environment:
     - DB_HOST=db
     - DB_USER=postgres
     - DB_PASSWORD=postgres
     - DB_NAME=tarefas
    depends_on:
      - db
    ports:
      - 3000:3000
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 5
      placement:
        constraints: [node.role==manager]
    
    