version: '3.8'
services:
  db:
    image: postgres:15.3
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tarefas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    deploy:
      placement:
        constraints: [node.role==worker]
  lista-tarefas:
    image: lista-tarefas
    deploy:
      placement:
        constraints: [node.role==worker]
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
     - DB_HOST=db
     - DB_USER=postgres
     - DB_PASSWORD=postgres
     - DB_NAME=tarefas
    depends_on:
      - db
    ports:
      - 3000:3000
    
    